x-airflow-common: &airflow-common
  build: .
  environment: &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__CORE__AUTH_MANAGER: airflow.providers.fab.auth_manager.fab_auth_manager.FabAuthManager

    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${AIRFLOW_DB_USER:-airflow}:${AIRFLOW_DB_PASSWORD:-airflow}@host.docker.internal:5432/${AIRFLOW_DB_NAME:-airflow}

    AIRFLOW__CORE__FERNET_KEY: "Z0mPUdKS8tNudnXdTRw8I056wMQKrlCzIPtBvljkD-A="
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "true"
    AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    AIRFLOW__SCHEDULER__ENABLE_HEALTH_CHECK: "true"
    AIRFLOW__CORE__EXECUTION_API_SERVER_URL: "http://airflow-apiserver:8080/execution/"
    AIRFLOW__API_AUTH__JWT_SECRET: "super-secret-jwt-key-change-this-in-production-2026"
    AIRFLOW__CORE__INTERNAL_API_SECRET_KEY: "another-strong-secret"
    AIRFLOW__API__SECRET_KEY: "yet-another-strong-secret"
    _PIP_ADDITIONAL_REQUIREMENTS: ${_PIP_ADDITIONAL_REQUIREMENTS:-}

    PYTHONPATH: /opt/airflow:/opt/airflow/src:/opt/spark/python:/opt/spark/python/lib/py4j-0.10.9.7-src.zip

    AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
    AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    AWS_S3_BUCKET: ${AWS_S3_BUCKET}
    AWS_S3_DATA_PARQUET_FILENAME: ${AWS_S3_DATA_PARQUET_FILENAME}
    PG_HOST: ${PG_HOST}
    PG_PORT: ${PG_PORT}
    PG_USER: ${PG_USER}
    PG_PASSWORD: ${PG_PASSWORD}
    PG_DATABASE: ${PG_DATABASE}
    DATASET_URL: ${DATASET_URL}

    JAVA_HOME: /usr/lib/jvm/java-17-openjdk-arm64

  volumes:
    - ./src:/opt/airflow/src          # Add this line
    - ./src/dags:/opt/airflow/dags    # Keep your existing one (or simplify)
    - ./airflow/logs:/opt/airflow/logs
    - ./airflow/plugins:/opt/airflow/plugins

  user: "${AIRFLOW_UID:-50000}:0"

  extra_hosts:
    - "host.docker.internal:host-gateway"

services:
  airflow-init:
    <<: *airflow-common
    container_name: airflow-init
    user: "0:0"
    entrypoint: /bin/bash
    command:
      - -c
      - |
        mkdir -p /opt/airflow/dags /opt/airflow/logs /opt/airflow/plugins
        chown -R "${AIRFLOW_UID:-50000}:0" /opt/airflow

        su -s /bin/bash airflow -c "
          airflow db migrate &&
          airflow users create \
            --username ${_AIRFLOW_WWW_USER_USERNAME:-airflow} \
            --firstname Airflow \
            --lastname Admin \
            --role Admin \
            --email admin@example.com \
            --password ${_AIRFLOW_WWW_USER_PASSWORD:-airflow}
        "
    environment:
      <<: *airflow-common-env
      _AIRFLOW_DB_MIGRATE: "true"
      _AIRFLOW_WWW_USER_CREATE: "true"
      _AIRFLOW_WWW_USER_USERNAME: ${_AIRFLOW_WWW_USER_USERNAME:-airflow}
      _AIRFLOW_WWW_USER_PASSWORD: ${_AIRFLOW_WWW_USER_PASSWORD:-airflow}

  airflow-apiserver:
    <<: *airflow-common
    container_name: airflow-apiserver
    command: api-server
    ports:
      - "8080:8080"
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:8080/api/v2/version" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always

  airflow-scheduler:
    <<: *airflow-common
    container_name: airflow-scheduler
    command: scheduler
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:8974/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always

  airflow-dag-processor:
    <<: *airflow-common
    container_name: airflow-dag-processor
    command: dag-processor
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    healthcheck:
      test: [ "CMD-SHELL", 'airflow jobs check --job-type DagProcessorJob --hostname "$${HOSTNAME}"' ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always

  postgres:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pg_data: