"""Update ingestion metadata table name

Revision ID: 0c8e1bb50981
Revises: e72a27ab6093
Create Date: 2026-03-28 15:27:36.726700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c8e1bb50981'
down_revision: Union[str, Sequence[str], None] = 'e72a27ab6093'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pipeline_step_runs', 'error_message',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pipeline_step_runs', 'error_message',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
