"""Make avg_resolution_time_in_minutes column nullable gold_nyc311_requests_by_complaint_daily table

Revision ID: 23c97b319717
Revises: 554cad02770d
Create Date: 2026-04-01 01:00:42.467341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23c97b319717'
down_revision: Union[str, Sequence[str], None] = '554cad02770d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gold_nyc311_requests_by_complaint_daily', 'avg_resolution_time_in_minutes',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gold_nyc311_requests_by_complaint_daily', 'avg_resolution_time_in_minutes',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    # ### end Alembic commands ###
