"""Create pipeline log tables

Revision ID: 43cc369248b5
Revises: 
Create Date: 2026-03-28 14:10:01.582085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43cc369248b5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_runs',
    sa.Column('pipeline_run_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pipeline_name', sa.String(), nullable=True),
    sa.Column('triggered_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('overall_status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('pipeline_run_id')
    )
    op.create_table('pipeline_step_runs',
    sa.Column('pipeline_step_run_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pipeline_run_id', sa.Integer(), nullable=False),
    sa.Column('dag_id', sa.String(), nullable=False),
    sa.Column('step_name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=False),
    sa.Column('num_records_in', sa.Integer(), nullable=False),
    sa.Column('num_records_out', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.pipeline_run_id'], ),
    sa.PrimaryKeyConstraint('pipeline_step_run_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pipeline_step_runs')
    op.drop_table('pipeline_runs')
    # ### end Alembic commands ###
