"""Remove s3_key from ingestion_metadata and add s3_file_key to pipeline_step_run table

Revision ID: 4d9ed6f063df
Revises: b34874dc2d8e
Create Date: 2026-03-29 21:03:30.963213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4d9ed6f063df'
down_revision: Union[str, Sequence[str], None] = 'b34874dc2d8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ingestion_metadata', 'pipeline_run_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('ingestion_metadata', 's3_key')
    op.alter_column('pipeline_runs', 'triggered_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.add_column('pipeline_step_runs', sa.Column('s3_file_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pipeline_step_runs', 's3_file_key')
    op.alter_column('pipeline_runs', 'triggered_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.add_column('ingestion_metadata', sa.Column('s3_key', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('ingestion_metadata', 'pipeline_run_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
