"""Create gold_nyc311_requests_by_complaint_daily table

Revision ID: 554cad02770d
Revises: bc5c1ee965db
Create Date: 2026-04-01 00:58:06.334201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '554cad02770d'
down_revision: Union[str, Sequence[str], None] = 'bc5c1ee965db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gold_nyc311_requests_by_complaint_daily',
    sa.Column('request_date', sa.Date(), nullable=False),
    sa.Column('complaint_type', sa.String(), nullable=False),
    sa.Column('total_requests', sa.Integer(), nullable=False),
    sa.Column('closed_requests', sa.Integer(), nullable=False),
    sa.Column('avg_resolution_time_in_minutes', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('request_date', 'complaint_type', name='pk_gold_nyc311_request_date_complaint_type')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gold_nyc311_requests_by_complaint_daily')
    # ### end Alembic commands ###
