"""Change resolution_time_in_minutes column name to resolution_time_in_hours

Revision ID: 7b01ad3b6140
Revises: 23c97b319717
Create Date: 2026-04-01 08:11:32.073194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7b01ad3b6140'
down_revision: Union[str, Sequence[str], None] = '23c97b319717'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fact_nyc311_service_requests', sa.Column('resolution_time_in_hours', sa.Float(), nullable=True))
    op.drop_column('fact_nyc311_service_requests', 'resolution_time_in_minutes')
    op.add_column('gold_nyc311_requests_by_complaint_daily', sa.Column('avg_resolution_time_in_hours', sa.Float(), nullable=True))
    op.drop_column('gold_nyc311_requests_by_complaint_daily', 'avg_resolution_time_in_minutes')
    op.add_column('gold_nyc311_requests_daily', sa.Column('avg_resolution_time_in_hours', sa.Float(), nullable=True))
    op.alter_column('gold_nyc311_requests_daily', 'request_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.Date(),
               existing_nullable=False)
    op.drop_column('gold_nyc311_requests_daily', 'avg_resolution_time_in_minutes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gold_nyc311_requests_daily', sa.Column('avg_resolution_time_in_minutes', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.alter_column('gold_nyc311_requests_daily', 'request_date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.drop_column('gold_nyc311_requests_daily', 'avg_resolution_time_in_hours')
    op.add_column('gold_nyc311_requests_by_complaint_daily', sa.Column('avg_resolution_time_in_minutes', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('gold_nyc311_requests_by_complaint_daily', 'avg_resolution_time_in_hours')
    op.add_column('fact_nyc311_service_requests', sa.Column('resolution_time_in_minutes', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('fact_nyc311_service_requests', 'resolution_time_in_hours')
    # ### end Alembic commands ###
