"""fix status column in extraction_metadata table

Revision ID: 8d11ca914db6
Revises: 4478cb7826d7
Create Date: 2026-03-24 15:29:23.336483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d11ca914db6'
down_revision: Union[str, Sequence[str], None] = '4478cb7826d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('extraction_metadata', sa.Column('status', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('extraction_metadata', 'status')
    # ### end Alembic commands ###
