"""Add pipeline_run_id to ingestion_metadata table

Revision ID: b34874dc2d8e
Revises: d7e8a75f0f5e
Create Date: 2026-03-28 23:43:31.835980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b34874dc2d8e'
down_revision: Union[str, Sequence[str], None] = 'd7e8a75f0f5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
