"""Remove columns from extraction_metadata table

Revision ID: b87f99cdf136
Revises: f45fc820ff1f
Create Date: 2026-03-24 18:18:13.483879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b87f99cdf136'
down_revision: Union[str, Sequence[str], None] = 'f45fc820ff1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('extraction_metadata', 'data_file_size_in_bytes')
    op.drop_column('extraction_metadata', 'data_file_path')
    op.drop_column('extraction_metadata', 'data_file_checksum')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('extraction_metadata', sa.Column('data_file_checksum', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('extraction_metadata', sa.Column('data_file_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('extraction_metadata', sa.Column('data_file_size_in_bytes', sa.BIGINT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
