"""Create initial tables

Revision ID: bc5c1ee965db
Revises: 
Create Date: 2026-04-01 00:40:25.049326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc5c1ee965db'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fact_nyc311_service_requests',
    sa.Column('unique_key', sa.Integer(), nullable=False),
    sa.Column('community_board', sa.String(), nullable=False),
    sa.Column('incident_zip', sa.String(), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('agency', sa.String(), nullable=False),
    sa.Column('complaint_type', sa.String(), nullable=False),
    sa.Column('descriptor', sa.String(), nullable=False),
    sa.Column('location_type', sa.String(), nullable=False),
    sa.Column('address_type', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('council_district', sa.String(), nullable=False),
    sa.Column('police_precinct', sa.String(), nullable=False),
    sa.Column('borough', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('resolution_time_in_minutes', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('unique_key')
    )
    op.create_table('gold_nyc311_requests_daily',
    sa.Column('request_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_requests', sa.Integer(), nullable=False),
    sa.Column('open_requests', sa.Integer(), nullable=False),
    sa.Column('closed_requests', sa.Integer(), nullable=False),
    sa.Column('pct_closed', sa.Float(), nullable=False),
    sa.Column('avg_resolution_time_in_minutes', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('request_date')
    )
    op.create_table('pipeline_step_runs',
    sa.Column('pipeline_step_run_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dag_id', sa.String(), nullable=False),
    sa.Column('step_name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=False),
    sa.Column('num_records_in', sa.Integer(), nullable=False),
    sa.Column('num_records_out', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('s3_file_key', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('pipeline_step_run_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pipeline_step_runs')
    op.drop_table('gold_nyc311_requests_daily')
    op.drop_table('fact_nyc311_service_requests')
    # ### end Alembic commands ###
