"""Create ingestion metadata table

Revision ID: cc58d44ea379
Revises: 43cc369248b5
Create Date: 2026-03-28 14:54:53.318326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc58d44ea379'
down_revision: Union[str, Sequence[str], None] = '43cc369248b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extraction_metadata',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('num_records_pulled', sa.Integer(), nullable=False),
    sa.Column('latest_record_created_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('s3_key', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('extraction_metadata')
    # ### end Alembic commands ###
