"""Add pipeline_run_id to ingestion_metadata table

Revision ID: d7e8a75f0f5e
Revises: 0c8e1bb50981
Create Date: 2026-03-28 21:28:53.823924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7e8a75f0f5e'
down_revision: Union[str, Sequence[str], None] = '0c8e1bb50981'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingestion_metadata', sa.Column('pipeline_run_id', sa.Integer(), nullable=True))
    op.add_column('ingestion_metadata', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.create_foreign_key(None, 'ingestion_metadata', 'pipeline_runs', ['pipeline_run_id'], ['pipeline_run_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ingestion_metadata', type_='foreignkey')
    op.drop_column('ingestion_metadata', 'created_at')
    op.drop_column('ingestion_metadata', 'pipeline_run_id')
    # ### end Alembic commands ###
