"""Update ingestion metadata table name

Revision ID: e72a27ab6093
Revises: cc58d44ea379
Create Date: 2026-03-28 15:06:15.688966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e72a27ab6093'
down_revision: Union[str, Sequence[str], None] = 'cc58d44ea379'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_metadata',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('num_records_pulled', sa.Integer(), nullable=False),
    sa.Column('latest_record_created_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('s3_key', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('extraction_metadata')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extraction_metadata',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('num_records_pulled', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('latest_record_created_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('s3_key', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('extraction_metadata_pkey'))
    )
    op.drop_table('ingestion_metadata')
    # ### end Alembic commands ###
