"""Fix records_in and records_out column definitions in pipeline_step_run table

Revision ID: ec2cd253bbdd
Revises: 7b01ad3b6140
Create Date: 2026-04-01 08:28:54.744193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec2cd253bbdd'
down_revision: Union[str, Sequence[str], None] = '7b01ad3b6140'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pipeline_step_runs', 'num_records_in',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('pipeline_step_runs', 'num_records_out',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pipeline_step_runs', 'num_records_out',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('pipeline_step_runs', 'num_records_in',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
