"""fix column definitions in extraction_metadata table

Revision ID: f45fc820ff1f
Revises: 8d11ca914db6
Create Date: 2026-03-24 15:32:18.299470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f45fc820ff1f'
down_revision: Union[str, Sequence[str], None] = '8d11ca914db6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('extraction_metadata', 'extraction_completed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('extraction_metadata', 'data_file_path',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('extraction_metadata', 'data_file_checksum',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('extraction_metadata', 'data_file_checksum',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('extraction_metadata', 'data_file_path',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('extraction_metadata', 'extraction_completed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    # ### end Alembic commands ###
